name: Generate and Deploy Documentation

on:
  workflow_call:

# Разрешение для работы с GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Отменяет одновременно запущенные сборки документации для экономии ресурсов
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # Doxyfile из Doxyfile.in
      - name: Configure CMake
        run: cmake -B build \
              -DPATCH_VERSION=${{ github.run_number }} \
              -DBUILD_DOCS=OFF

      - name: Run Doxygen via CMake
        run: cmake --build build --target doc

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/html' 

      # Публикация артефакта на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

